version: "3.8"

networks:
  se-net: {}

services:
  app:
    build: .
    container_name: se-app
    restart: always
    environment:
      PORT: ${PORT}
      API_HOST: ${API_HOST}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_PORT: ${MONGO_PORT}
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    networks:
      - se-net
  mongo:
    image: mongo
    container_name: se-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      - se-net
    volumes:
      - mongo_vol:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin -u ${MONGO_USER} -p ${MONGO_PASSWORD} --quiet | grep 1
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_vol:
