version: "3.8"

services:
  mongo:
    image: mongo
    container_name: se-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_vol:/data/db
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin -u ${MONGO_USER} -p ${MONGO_PASSWORD} --quiet | grep 1
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_vol:
